import { Address, LocalFile } from './reference';
import { Users } from './user';
export type AdProcess = 'CREATED' | 'DOING' | 'DONE';
export type Advertisement = {
  id: number;
  mainDirectionId: number;
  directionId: number;
  subDirectionId: number;
  categoryId: number;
  provinceId: number;
  province: Address;
  districtId: number;
  district: Address;
  khorooId: number;
  khoroo: Address;
  title: string;
  address: string;
  desciption: string;
  price: number;
  counter: number;
  email: string;
  phone: string;
  isMessenger: boolean;
  isTermOfService: boolean;
  rating: number;
  images: LocalFile[];
  saveUsers: Users[];
  createdBy: number;
  createdUser?: Users;
  createdAt: string;
  doingBy: number;
  process: AdProcess;
};